import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import    NavbarWrapper from "./(compontent)/Navbar/NavbarWrapper"
import Footer from "./(compontent)/footer/footer"
import Providerredux from "./slice/provider"
import  { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
title: "GoCartApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providerredux>
  <NavbarWrapper/>                  
        {children}
        <Toaster/>
        <Footer/>
        </Providerredux>
      
        </body>
    </html>
  );
}
